site_name: django-statusboard
site_description: A Django based status page
site_author: Emanuele Di Giacomo <emanuele@digiacomo.cc>
copyright: Copyright (C) 2017 Emanuele Di Giacomo <emanuele@digiacomo.cc>
repo_url: https://github.com/edigiacomo/django-statusboard
pages:
    - Home: index.md
    
theme: readthedocs
