# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-17 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusboard', '0009_auto_20170217_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicegroup',
            name='collapse',
            field=models.IntegerField(choices=[(0, 'Non collassare mai'), (1, 'Collassa sempre'), (2, 'Collapse when a service is not operational')], default=0),
        ),
    ]
