# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusboard', '0012_auto_20170217_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicegroup',
            name='collapse',
            field=models.IntegerField(choices=[(0, 'Never collapse'), (1, 'Always collapse'), (2, 'Collapse when all the services are operational')], default=0),
        ),
    ]
