# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statusboard', '0014_incident_closed'),
        ('statusboard', '0014_merge_20170222_2054'),
    ]

    operations = [
    ]
