# Generated by Django 4.2.7 on 2023-11-27 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("statusboard", "0022_auto_20201204_0856"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="status_modified",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="last change of status"),
        ),
    ]
