name: Build
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    name: Python ${{ matrix.python }} - Django ${{ matrix.django }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.6", "3.7", "3.8", "3.9", "3.10"]
        django: [22, 32]
    steps:
      - name: Install system dependencies
        run: pip install tox
      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: tox -e py-django${{ matrix.django }}
      - name: Run codecov
        run: |
          pip install .
          pip install -r requirements/requirements-coverage.txt
          pip install codecov
          codecov
        if: matrix.python == '3.9' && matrix.django == '32'
