name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8, 3.9]
        django: [22, 31, 32]
    steps:
      - name: Install system dependencies
        run: |
          sudo apt install -y pandoc
          pip install tox tox-travis flake8 codecov
      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: tox -e py-django${{ matrix.django }}
      - name: Run codecov
        run: codecov
