name: Build
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    name: Python ${{ matrix.python }} - Django ${{ matrix.django }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
        django: [32, 41, 42]
        exclude:
          - python: "3.6"
            django: 41
          - python: "3.6"
            django: 42
          - python: "3.7"
            django: 42
    steps:
      - name: Install system dependencies
        run: pip install tox
      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        run: tox -e py-django${{ matrix.django }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        if: matrix.python == '3.9' && matrix.django == '32'
