name: Build
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    name: Python ${{ matrix.python }} - Django ${{ matrix.django }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - python: "3.6"
            py: 36
            django: 32
          - python: "3.7"
            py: 37
            django: 32
          - python: "3.8"
            py: 38
            django: 32
          - python: "3.9"
            py: 39
            django: 32
          - python: "3.9"
            py: 39
            django: 42
          - python: "3.10"
            py: 310
            django: 32
          - python: "3.10"
            py: 310
            django: 42
          - python: "3.10"
            py: 310
            django: 50
          - python: "3.11"
            py: 311
            django: 32
          - python: "3.11"
            py: 311
            django: 42
          - python: "3.11"
            py: 311
            django: 50
    steps:
      - name: Install system dependencies
        run: pip install tox
      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        run: tox -e py${{ matrix.py }}-django${{ matrix.django }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        if: matrix.python == '3.11' && matrix.django == '42'
