name: Docs
on:
  push:
jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Install system dependencies
        run: pip install tox
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run mkdocs
        run: tox -e docs
